version: '3.3'

# volumes:
#   my-volumes:
volumes:
    wordpress:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/Desktop/Inception/srcs/wordpress
    mariadb:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/Desktop/Inception/srcs/mariadb
networks:
  my-inception:

services:

  nginx:
      build: ./requirements/nginx/.
      container_name: nginx 
      image: nginx
      ports:
        - "443:443"      
      restart: always
      depends_on:
        - wordpress
      networks:
        - my-inception
      volumes:
        - wordpress:/var/www/html/wop
  mariadb:
      build: ./requirements/mariadb/.
      container_name: mariadb
      image: mariadb
      restart: always
      env_file:
        - .env
      networks:
        - my-inception
      volumes:
        - mariadb:/var/lib/mysql
  wordpress:
      build: ./requirements/wordpress/.
      container_name: wordpress
      image: wordpress
      restart: always
      depends_on:
        - mariadb
      networks:
        - my-inception
      env_file:
        - .env
      volumes:
        - wordpress:/var/www/html/wop
  mywebsite:
        container_name: mywebsite
        build: ./requirements/bonus/mywebsite/.
        image: mywebsite
        ports: 
          - 8800:1337
  adminer:
        container_name: adminer
        build: requirements/bonus/adminer/.
        image: adminer
        ports:
          - "8080:8080"
        networks:
          - my-inception
        restart: always
  cadvisor:
        build: ./requirements/bonus/cadvisor/.
        container_name: cadvisor
        image: cadvisor
        restart: always
        ports:
          - 8082:8080
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        networks:
          - my-inception
  redis:
        build: ./requirements/bonus/redis/.
        container_name: redis
        image: redis
        restart: always
        ports: 
          - 6379:6379
        volumes:
          - wordpress:/var/www/html/wop
        networks:
          - my-inception


