version: '3.3'

volumes:
  my-volumes:

networks:
  my-inception:

services:

  nginx:
      build: ./requirements/nginx/.
      container_name: nginx 
      # image: nginx
      ports:
        - "443:443"      
      restart: on-failure
      depends_on:
        - wordpress
      networks:
        - my-inception
      volumes:
        - my-volumes:/var/www/html/
  mariadb:
      build: ./requirements/mariadb/.
      container_name: mariadb
      # image: mariadb
      restart: on-failure
      env_file:
        - .env
      networks:
        - my-inception
      volumes:
        - my-volumes:/var/www/html/
  wordpress:
      build: ./requirements/wordpress/.
      container_name: wordpress   
      restart: on-failure
      depends_on:
        - mariadb
      networks:
        - my-inception
      env_file:
        - .env
      volumes:
        - my-volumes:/var/www/html/wop

