version: '3.3'

# volumes:
#   my-volumes:
volumes:
    mariadb-data:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/data/mariadb
    wordpress-data:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/data/wordpress
networks:
  my-inception:

services:

  nginx:
      build: ./requirements/nginx/.
      container_name: nginx 
      image: nginx
      ports:
        - "443:443"      
      restart: always
      depends_on:
        - wordpress
      networks:
        - my-inception
      volumes:
        - wordpress-data:/var/www/html/wop
  mariadb:
      build: ./requirements/mariadb/.
      container_name: mariadb
      image: mariadb
      restart: always
      env_file:
        - .env
      networks:
        - my-inception
      # volumes:
      #   - mariadb-data:/var/lib/mysql
  wordpress:
      build: ./requirements/wordpress/.
      container_name: wordpress
      image: wordpress
      restart: always
      depends_on:
        - mariadb
      networks:
        - my-inception
      env_file:
        - .env
      volumes:
        - wordpress-data:/var/www/html/wop
  mywebsite:
        container_name: mywebsite
        build: ./requirements/bonus/mywebsite/.
        image: mywebsite
        ports: 
          - 8000:1337
  adminer:
        container_name: adminer
        build: requirements/bonus/adminer/.
        image: adminer
        ports:
          - "8080:8080"
        networks:
          - my-inception
        restart: always


