version: '3.3'

volumes:
    v_wordpress:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/Desktop/Inception/wordpress
    v_mariadb:
      driver_opts:
        type: none
        o: bind
        device: /Users/imabid/Desktop/Inception/mariadb
networks:
  my-inception:

services:

  nginx:
      build: ./requirements/nginx/.
      container_name: nginx 
      image: nginx
      ports:
        - 443:443
      restart: on-failure
      depends_on:
        - wordpress
      networks:
        - my-inception
      volumes:
        - v_wordpress:/var/www/html/wop
  mariadb:
      build: ./requirements/mariadb/.
      container_name: mariadb
      image: mariadb
      restart: on-failure
      env_file:
        - .env
      networks:
        - my-inception
      volumes:
        - v_mariadb:/var/lib/mysql
  wordpress:
      build: ./requirements/wordpress/.
      container_name: wordpress
      image: wordpress
      restart: on-failure
      depends_on:
        - mariadb
      networks:
        - my-inception
      env_file:
        - .env
      volumes:
        - v_wordpress:/var/www/html/wop
  mywebsite:
        container_name: mywebsite
        build: ./requirements/bonus/mywebsite/.
        image: mywebsite
        ports: 
          - 1337:1337
  adminer:
        container_name: adminer
        build: requirements/bonus/adminer/.
        image: adminer
        ports:
          - "8080:8080"
        networks:
          - my-inception
        restart: on-failure
  cadvisor:
        build: ./requirements/bonus/cadvisor/.
        container_name: cadvisor
        image: cadvisor
        restart: on-failure
        ports:
          - 6464:8080
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        networks:
          - my-inception
  redis:
        build: ./requirements/bonus/redis/.
        container_name: redis
        image: redis
        restart: on-failure
        ports: 
          - 6379:6379
        volumes:
          - v_wordpress:/var/www/html/wop
        networks:
          - my-inception
  ftp:
        container_name: ftp
        build: ./requirements/bonus/ftp/
        image: ftp
        volumes:
          - v_wordpress:/home/imabid/ftp/files
        env_file:
          - .env
        ports:
          - "21:21"
          - "20:20"
          - "40000-40005:40000-40005"
        networks:
          - my-inception
        restart: on-failure